### ISSUE TITLE
Stuck trying to connect to lights.

### ISSUE THREAD

**Issue by FakeKitten** [RandoMixs/yeelight-beatsaber#1]
I have several yeelight bulbs all of which have LAN Control enabled and I have commented out the line requiring the name BeatLight.

```
C:\Users\Fish\Downloads\yeelight-beatsaber-master>node index.js
 [TCP]  Servidor criado
 [WebSocket]  Tentando conexão com o Beat Saber...
 [Yeelight]  As lampadas irão se conectar ao seu computador atravês do IP 192.168.1.64
 [Yeelight]  Procurando as lampadas...
 [WebSocket]  Conectado
```

Is it possible to edit things and manually specify the IP of each bulb?

**Comment by RandoMixs** [comment]
You can specify the IP of each bulb by editing the package "yeelight2"
(I even had problems with not finding the bulbs too)

This is unfortunately a yeelight2 package issue.
